// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UniScheduler.Infrastructure.Persistence;

#nullable disable

namespace UniScheduler.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260603171515_AddPhysicalEducationHours")]
    partial class AddPhysicalEducationHours
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UniScheduler.Domain.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("PasswordResetExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordResetTokenHash")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("TeacherId")
                        .HasColumnType("uuid");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("\"Email\" IS NOT NULL");

                    b.HasIndex("TeacherId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("UniScheduler.Domain.Entities.Building", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NumberOfBasementFloors")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("NumberOfFloors")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(5);

                    b.Property<string>("ShortCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("UniversityId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UniversityId");

                    b.ToTable("Buildings");
                });

            modelBuilder.Entity("UniScheduler.Domain.Entities.BuildingDistance", b =>
                {
                    b.Property<Guid>("FromBuildingId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ToBuildingId")
                        .HasColumnType("uuid");

                    b.Property<int>("DistanceMeters")
                        .HasColumnType("integer");

                    b.HasKey("FromBuildingId", "ToBuildingId");

                    b.HasIndex("ToBuildingId");

                    b.ToTable("BuildingDistances");
                });

            modelBuilder.Entity("UniScheduler.Domain.Entities.CalendarPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AcademicYear")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Term")
                        .HasColumnType("integer");

                    b.Property<Guid>("UniversityId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UniversityId");

                    b.ToTable("CalendarPlans");
                });

            modelBuilder.Entity("UniScheduler.Domain.Entities.CalendarWeek", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CalendarPlanId")
                        .HasColumnType("uuid");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<string>("Note")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("CalendarPlanId", "StartDate")
                        .IsUnique();

                    b.ToTable("CalendarWeeks");
                });

            modelBuilder.Entity("UniScheduler.Domain.Entities.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("FacultyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ShortCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("FacultyId");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("UniScheduler.Domain.Entities.EntranceConnection", b =>
                {
                    b.Property<Guid>("FromNodeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ToBuildingId")
                        .HasColumnType("uuid");

                    b.Property<int>("DistanceMeters")
                        .HasColumnType("integer");

                    b.Property<Guid>("FromBuildingId")
                        .HasColumnType("uuid");

                    b.HasKey("FromNodeId", "ToBuildingId");

                    b.HasIndex("FromBuildingId");

                    b.HasIndex("ToBuildingId");

                    b.ToTable("EntranceConnections");
                });

            modelBuilder.Entity("UniScheduler.Domain.Entities.Faculty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ShortCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("UniversityId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UniversityId", "ShortCode")
                        .IsUnique();

                    b.ToTable("Faculties");
                });

            modelBuilder.Entity("UniScheduler.Domain.Entities.FloorPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BuildingId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("FloorPlanJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId")
                        .IsUnique()
                        .HasFilter("\"IsActive\" = TRUE");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("FloorPlans");
                });

            modelBuilder.Entity("UniScheduler.Domain.Entities.FloorPlanDraft", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BuildingId")
                        .HasColumnType("uuid");

                    b.Property<string>("DraftJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsOpenToAdmins")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("BuildingId", "OwnerUserId");

                    b.ToTable("FloorPlanDrafts");
                });

            modelBuilder.Entity("UniScheduler.Domain.Entities.FloorPlanEdge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BuildingId")
                        .HasColumnType("uuid");

                    b.Property<int>("DistanceMeters")
                        .HasColumnType("integer");

                    b.Property<Guid>("FromNodeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ToNodeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.HasIndex("FromNodeId");

                    b.HasIndex("ToNodeId");

                    b.ToTable("FloorPlanEdges");
                });

            modelBuilder.Entity("UniScheduler.Domain.Entities.FloorPlanNode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BuildingId")
                        .HasColumnType("uuid");

                    b.Property<int>("Floor")
                        .HasColumnType("integer");

                    b.Property<string>("Label")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("NodeType")
                        .HasColumnType("integer");

                    b.Property<Guid?>("RoomId")
                        .HasColumnType("uuid");

                    b.Property<double>("X")
                        .HasColumnType("double precision");

                    b.Property<double>("Y")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.HasIndex("RoomId");

                    b.ToTable("FloorPlanNodes");
                });

            modelBuilder.Entity("UniScheduler.Domain.Entities.GroupBlockedDay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GroupId", "DayOfWeek")
                        .IsUnique();

                    b.ToTable("GroupBlockedDays");
                });

            modelBuilder.Entity("UniScheduler.Domain.Entities.Invitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ConsumedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InvitedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("OtpHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("SystemRole")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid?>("TeacherId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UniversityId")
                        .HasColumnType("uuid");

                    b.Property<int>("UniversityRole")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ConsumedByUserId");

                    b.HasIndex("Email");

                    b.HasIndex("InvitedByUserId");

                    b.HasIndex("OtpHash")
                        .IsUnique();

                    b.HasIndex("TeacherId");

                    b.HasIndex("UniversityId");

                    b.ToTable("Invitations");
                });

            modelBuilder.Entity("UniScheduler.Domain.Entities.PairTimeSlot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<int>("PairNumber")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone");

                    b.Property<Guid>("UniversityId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UniversityId", "PairNumber")
                        .IsUnique();

                    b.ToTable("PairTimeSlots");
                });

            modelBuilder.Entity("UniScheduler.Domain.Entities.RescheduleRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdminNote")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OriginalEntryId")
                        .HasColumnType("uuid");

                    b.Property<int?>("ProposedDayOfWeek")
                        .HasColumnType("integer");

                    b.Property<bool>("ProposedIsOnline")
                        .HasColumnType("boolean");

                    b.Property<int?>("ProposedPairNumber")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ProposedRoomId")
                        .HasColumnType("uuid");

                    b.Property<int?>("ProposedWeekType")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RequestedByTeacherId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OriginalEntryId");

                    b.HasIndex("ProposedRoomId");

                    b.HasIndex("RequestedByTeacherId");

                    b.ToTable("RescheduleRequests");
                });

            modelBuilder.Entity("UniScheduler.Domain.Entities.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AllowedLessonTypes")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValueSql("''");

                    b.Property<Guid>("BuildingId")
                        .HasColumnType("uuid");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<int>("Floor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<bool>("HasComputers")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasLab")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasProjector")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDistributed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsOnline")
                        .HasColumnType("boolean");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("RoomType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("UniScheduler.Domain.Entities.Schedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AcademicYear")
                        .HasColumnType("integer");

                    b.Property<bool>("AllowCrossFacultyLessons")
                        .HasColumnType("boolean");

                    b.Property<int?>("BaseScore")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<Guid?>("FacultyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GenerationNotes")
                        .HasColumnType("text");

                    b.Property<bool>("IsOpenToAdmins")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Term")
                        .HasColumnType("integer");

                    b.Property<Guid>("UniversityId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FacultyId");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("UniversityId");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("UniScheduler.Domain.Entities.ScheduleEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("boolean");

                    b.Property<int>("LessonType")
                        .HasColumnType("integer");

                    b.Property<int>("PairNumber")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ParallelGroupId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RoomId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("uuid");

                    b.Property<string>("SubgroupLabel")
                        .HasColumnType("text");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uuid");

                    b.Property<int>("WeekType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherId");

                    b.HasIndex("ScheduleId", "RoomId", "DayOfWeek", "PairNumber", "WeekType")
                        .IsUnique()
                        .HasFilter("\"RoomId\" IS NOT NULL AND \"ParallelGroupId\" IS NULL");

                    b.HasIndex("ScheduleId", "TeacherId", "DayOfWeek", "PairNumber", "WeekType")
                        .IsUnique()
                        .HasFilter("\"ParallelGroupId\" IS NULL");

                    b.ToTable("ScheduleEntries");
                });

            modelBuilder.Entity("UniScheduler.Domain.Entities.ScheduleEntryStudentGroup", b =>
                {
                    b.Property<Guid>("ScheduleEntryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StudentGroupId")
                        .HasColumnType("uuid");

                    b.HasKey("ScheduleEntryId", "StudentGroupId");

                    b.HasIndex("StudentGroupId");

                    b.ToTable("ScheduleEntryStudentGroups");
                });

            modelBuilder.Entity("UniScheduler.Domain.Entities.SolverSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ActiveDay")
                        .HasColumnType("integer");

                    b.Property<int>("ConsecLab")
                        .HasColumnType("integer");

                    b.Property<int>("ConsecLecture")
                        .HasColumnType("integer");

                    b.Property<int>("ConsecPractical")
                        .HasColumnType("integer");

                    b.Property<int>("ConsecRunScalar")
                        .HasColumnType("integer");

                    b.Property<int>("ConsecSeminar")
                        .HasColumnType("integer");

                    b.Property<int>("DepartmentMismatchPenalty")
                        .HasColumnType("integer");

                    b.Property<int>("EarlyPair")
                        .HasColumnType("integer");

                    b.Property<int>("LatePair")
                        .HasColumnType("integer");

                    b.Property<int>("MiddlePair")
                        .HasColumnType("integer");

                    b.Property<int>("SanPinOverload")
                        .HasColumnType("integer");

                    b.Property<int>("SaturdayPenalty")
                        .HasColumnType("integer");

                    b.Property<int>("StairFloorMeters")
                        .HasColumnType("integer");

                    b.Property<int>("StudentWindow")
                        .HasColumnType("integer");

                    b.Property<int>("TeacherWindow")
                        .HasColumnType("integer");

                    b.Property<Guid>("UniversityId")
                        .HasColumnType("uuid");

                    b.Property<int>("WalkingPenaltyMax")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UniversityId");

                    b.ToTable("SolverSettings");
                });

            modelBuilder.Entity("UniScheduler.Domain.Entities.StudentGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DegreeType")
                        .HasColumnType("integer");

                    b.Property<Guid>("FacultyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StudentCount")
                        .HasColumnType("integer");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FacultyId");

                    b.ToTable("StudentGroups");
                });

            modelBuilder.Entity("UniScheduler.Domain.Entities.StudyPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AcademicYear")
                        .HasColumnType("integer");

                    b.Property<Guid?>("CalendarPlanId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("FacultyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Term")
                        .HasColumnType("integer");

                    b.Property<Guid>("UniversityId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CalendarPlanId");

                    b.HasIndex("FacultyId");

                    b.HasIndex("UniversityId");

                    b.ToTable("StudyPlans");
                });

            modelBuilder.Entity("UniScheduler.Domain.Entities.StudyPlanEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("LabHours")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.0);

                    b.Property<double>("LanguageHours")
                        .HasColumnType("double precision");

                    b.Property<double>("LectureHours")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.0);

                    b.Property<double>("PhysicalEducationHours")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.0);

                    b.Property<double>("PracticalHours")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.0);

                    b.Property<double>("SeminarHours")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.0);

                    b.Property<Guid>("StudyPlanId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid");

                    b.Property<double>("ThesisHours")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.HasIndex("StudyPlanId", "SubjectId")
                        .IsUnique();

                    b.ToTable("StudyPlanEntries");
                });

            modelBuilder.Entity("UniScheduler.Domain.Entities.StudyPlanGroup", b =>
                {
                    b.Property<Guid>("StudyPlanId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StudentGroupId")
                        .HasColumnType("uuid");

                    b.HasKey("StudyPlanId", "StudentGroupId");

                    b.HasIndex("StudentGroupId");

                    b.ToTable("StudyPlanGroups");
                });

            modelBuilder.Entity("UniScheduler.Domain.Entities.Subject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AcademicYear")
                        .HasColumnType("integer");

                    b.Property<bool>("AllowsSubgroups")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SubgroupCount")
                        .HasColumnType("integer");

                    b.Property<int>("Term")
                        .HasColumnType("integer");

                    b.Property<Guid>("UniversityId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("UniversityId");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("UniScheduler.Domain.Entities.Teacher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UniversityId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UniversityId", "Email")
                        .IsUnique();

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("UniScheduler.Domain.Entities.TeacherAvailability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("boolean");

                    b.Property<int>("PairNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("ValidFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ValidTo")
                        .HasColumnType("date");

                    b.Property<int>("WeekType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.ToTable("TeacherAvailabilities");
                });

            modelBuilder.Entity("UniScheduler.Domain.Entities.TeacherSubject", b =>
                {
                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid");

                    b.Property<int>("LessonType")
                        .HasColumnType("integer");

                    b.Property<int?>("PreferredRoomType")
                        .HasColumnType("integer");

                    b.HasKey("TeacherId", "SubjectId", "LessonType");

                    b.HasIndex("SubjectId");

                    b.ToTable("TeacherSubjects");
                });

            modelBuilder.Entity("UniScheduler.Domain.Entities.University", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("City")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ShortName")
                        .IsUnique();

                    b.ToTable("Universities");
                });

            modelBuilder.Entity("UniScheduler.Domain.Entities.UserUniversityAccess", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UniversityId")
                        .HasColumnType("uuid");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "UniversityId");

                    b.HasIndex("UniversityId");

                    b.ToTable("UserUniversityAccesses");
                });

            modelBuilder.Entity("UniScheduler.Domain.Entities.AppUser", b =>
                {
                    b.HasOne("UniScheduler.Domain.Entities.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("UniScheduler.Domain.Entities.Building", b =>
                {
                    b.HasOne("UniScheduler.Domain.Entities.University", "University")
                        .WithMany("Buildings")
                        .HasForeignKey("UniversityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("University");
                });

            modelBuilder.Entity("UniScheduler.Domain.Entities.BuildingDistance", b =>
                {
                    b.HasOne("UniScheduler.Domain.Entities.Building", "FromBuilding")
                        .WithMany("DistancesFrom")
                        .HasForeignKey("FromBuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniScheduler.Domain.Entities.Building", "ToBuilding")
                        .WithMany("DistancesTo")
                        .HasForeignKey("ToBuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FromBuilding");

                    b.Navigation("ToBuilding");
                });

            modelBuilder.Entity("UniScheduler.Domain.Entities.CalendarPlan", b =>
                {
                    b.HasOne("UniScheduler.Domain.Entities.University", "University")
                        .WithMany("CalendarPlans")
                        .HasForeignKey("UniversityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("University");
                });

            modelBuilder.Entity("UniScheduler.Domain.Entities.CalendarWeek", b =>
                {
                    b.HasOne("UniScheduler.Domain.Entities.CalendarPlan", "CalendarPlan")
                        .WithMany("Weeks")
                        .HasForeignKey("CalendarPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CalendarPlan");
                });

            modelBuilder.Entity("UniScheduler.Domain.Entities.Department", b =>
                {
                    b.HasOne("UniScheduler.Domain.Entities.Faculty", "Faculty")
                        .WithMany("Departments")
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Faculty");
                });

            modelBuilder.Entity("UniScheduler.Domain.Entities.EntranceConnection", b =>
                {
                    b.HasOne("UniScheduler.Domain.Entities.Building", "FromBuilding")
                        .WithMany()
                        .HasForeignKey("FromBuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniScheduler.Domain.Entities.FloorPlanNode", "FromNode")
                        .WithMany("Connections")
                        .HasForeignKey("FromNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniScheduler.Domain.Entities.Building", "ToBuilding")
                        .WithMany()
                        .HasForeignKey("ToBuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FromBuilding");

                    b.Navigation("FromNode");

                    b.Navigation("ToBuilding");
                });

            modelBuilder.Entity("UniScheduler.Domain.Entities.Faculty", b =>
                {
                    b.HasOne("UniScheduler.Domain.Entities.University", "University")
                        .WithMany("Faculties")
                        .HasForeignKey("UniversityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("University");
                });

            modelBuilder.Entity("UniScheduler.Domain.Entities.FloorPlan", b =>
                {
                    b.HasOne("UniScheduler.Domain.Entities.Building", "Building")
                        .WithMany("FloorPlans")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniScheduler.Domain.Entities.AppUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Building");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("UniScheduler.Domain.Entities.FloorPlanDraft", b =>
                {
                    b.HasOne("UniScheduler.Domain.Entities.Building", "Building")
                        .WithMany()
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniScheduler.Domain.Entities.AppUser", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("UniScheduler.Domain.Entities.FloorPlanEdge", b =>
                {
                    b.HasOne("UniScheduler.Domain.Entities.Building", "Building")
                        .WithMany("FloorPlanEdges")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniScheduler.Domain.Entities.FloorPlanNode", "FromNode")
                        .WithMany("EdgesFrom")
                        .HasForeignKey("FromNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniScheduler.Domain.Entities.FloorPlanNode", "ToNode")
                        .WithMany("EdgesTo")
                        .HasForeignKey("ToNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");

                    b.Navigation("FromNode");

                    b.Navigation("ToNode");
                });

            modelBuilder.Entity("UniScheduler.Domain.Entities.FloorPlanNode", b =>
                {
                    b.HasOne("UniScheduler.Domain.Entities.Building", "Building")
                        .WithMany("FloorPlanNodes")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniScheduler.Domain.Entities.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Building");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("UniScheduler.Domain.Entities.GroupBlockedDay", b =>
                {
                    b.HasOne("UniScheduler.Domain.Entities.StudentGroup", "Group")
                        .WithMany("BlockedDays")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("UniScheduler.Domain.Entities.Invitation", b =>
                {
                    b.HasOne("UniScheduler.Domain.Entities.AppUser", "ConsumedBy")
                        .WithMany()
                        .HasForeignKey("ConsumedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("UniScheduler.Domain.Entities.AppUser", "InvitedBy")
                        .WithMany()
                        .HasForeignKey("InvitedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UniScheduler.Domain.Entities.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("UniScheduler.Domain.Entities.University", "University")
                        .WithMany()
                        .HasForeignKey("UniversityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConsumedBy");

                    b.Navigation("InvitedBy");

                    b.Navigation("Teacher");

                    b.Navigation("University");
                });

            modelBuilder.Entity("UniScheduler.Domain.Entities.PairTimeSlot", b =>
                {
                    b.HasOne("UniScheduler.Domain.Entities.University", "University")
                        .WithMany()
                        .HasForeignKey("UniversityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("University");
                });

            modelBuilder.Entity("UniScheduler.Domain.Entities.RescheduleRequest", b =>
                {
                    b.HasOne("UniScheduler.Domain.Entities.ScheduleEntry", "OriginalEntry")
                        .WithMany()
                        .HasForeignKey("OriginalEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniScheduler.Domain.Entities.Room", "ProposedRoom")
                        .WithMany()
                        .HasForeignKey("ProposedRoomId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("UniScheduler.Domain.Entities.Teacher", "RequestedByTeacher")
                        .WithMany()
                        .HasForeignKey("RequestedByTeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OriginalEntry");

                    b.Navigation("ProposedRoom");

                    b.Navigation("RequestedByTeacher");
                });

            modelBuilder.Entity("UniScheduler.Domain.Entities.Room", b =>
                {
                    b.HasOne("UniScheduler.Domain.Entities.Building", "Building")
                        .WithMany("Rooms")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniScheduler.Domain.Entities.Department", "Department")
                        .WithMany("Rooms")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Building");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("UniScheduler.Domain.Entities.Schedule", b =>
                {
                    b.HasOne("UniScheduler.Domain.Entities.Faculty", "Faculty")
                        .WithMany()
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("UniScheduler.Domain.Entities.AppUser", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("UniScheduler.Domain.Entities.University", "University")
                        .WithMany()
                        .HasForeignKey("UniversityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Faculty");

                    b.Navigation("Owner");

                    b.Navigation("University");
                });

            modelBuilder.Entity("UniScheduler.Domain.Entities.ScheduleEntry", b =>
                {
                    b.HasOne("UniScheduler.Domain.Entities.Room", "Room")
                        .WithMany("ScheduleEntries")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("UniScheduler.Domain.Entities.Schedule", "Schedule")
                        .WithMany("Entries")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniScheduler.Domain.Entities.Subject", "Subject")
                        .WithMany("ScheduleEntries")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniScheduler.Domain.Entities.Teacher", "Teacher")
                        .WithMany("ScheduleEntries")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("Schedule");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("UniScheduler.Domain.Entities.ScheduleEntryStudentGroup", b =>
                {
                    b.HasOne("UniScheduler.Domain.Entities.ScheduleEntry", "ScheduleEntry")
                        .WithMany("StudentGroups")
                        .HasForeignKey("ScheduleEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniScheduler.Domain.Entities.StudentGroup", "StudentGroup")
                        .WithMany("ScheduleEntryGroups")
                        .HasForeignKey("StudentGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScheduleEntry");

                    b.Navigation("StudentGroup");
                });

            modelBuilder.Entity("UniScheduler.Domain.Entities.SolverSettings", b =>
                {
                    b.HasOne("UniScheduler.Domain.Entities.University", "University")
                        .WithMany("SolverSettings")
                        .HasForeignKey("UniversityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("University");
                });

            modelBuilder.Entity("UniScheduler.Domain.Entities.StudentGroup", b =>
                {
                    b.HasOne("UniScheduler.Domain.Entities.Faculty", "Faculty")
                        .WithMany("Groups")
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Faculty");
                });

            modelBuilder.Entity("UniScheduler.Domain.Entities.StudyPlan", b =>
                {
                    b.HasOne("UniScheduler.Domain.Entities.CalendarPlan", "CalendarPlan")
                        .WithMany("StudyPlans")
                        .HasForeignKey("CalendarPlanId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("UniScheduler.Domain.Entities.Faculty", "Faculty")
                        .WithMany()
                        .HasForeignKey("FacultyId");

                    b.HasOne("UniScheduler.Domain.Entities.University", "University")
                        .WithMany()
                        .HasForeignKey("UniversityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CalendarPlan");

                    b.Navigation("Faculty");

                    b.Navigation("University");
                });

            modelBuilder.Entity("UniScheduler.Domain.Entities.StudyPlanEntry", b =>
                {
                    b.HasOne("UniScheduler.Domain.Entities.StudyPlan", "StudyPlan")
                        .WithMany("Entries")
                        .HasForeignKey("StudyPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniScheduler.Domain.Entities.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudyPlan");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("UniScheduler.Domain.Entities.StudyPlanGroup", b =>
                {
                    b.HasOne("UniScheduler.Domain.Entities.StudentGroup", "StudentGroup")
                        .WithMany()
                        .HasForeignKey("StudentGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniScheduler.Domain.Entities.StudyPlan", "StudyPlan")
                        .WithMany("Groups")
                        .HasForeignKey("StudyPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudentGroup");

                    b.Navigation("StudyPlan");
                });

            modelBuilder.Entity("UniScheduler.Domain.Entities.Subject", b =>
                {
                    b.HasOne("UniScheduler.Domain.Entities.Department", "Department")
                        .WithMany("Subjects")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("UniScheduler.Domain.Entities.University", "University")
                        .WithMany()
                        .HasForeignKey("UniversityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("University");
                });

            modelBuilder.Entity("UniScheduler.Domain.Entities.Teacher", b =>
                {
                    b.HasOne("UniScheduler.Domain.Entities.University", "University")
                        .WithMany("Teachers")
                        .HasForeignKey("UniversityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("University");
                });

            modelBuilder.Entity("UniScheduler.Domain.Entities.TeacherAvailability", b =>
                {
                    b.HasOne("UniScheduler.Domain.Entities.Teacher", "Teacher")
                        .WithMany("Availabilities")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("UniScheduler.Domain.Entities.TeacherSubject", b =>
                {
                    b.HasOne("UniScheduler.Domain.Entities.Subject", "Subject")
                        .WithMany("TeacherSubjects")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniScheduler.Domain.Entities.Teacher", "Teacher")
                        .WithMany("TeacherSubjects")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("UniScheduler.Domain.Entities.UserUniversityAccess", b =>
                {
                    b.HasOne("UniScheduler.Domain.Entities.University", "University")
                        .WithMany("UserAccesses")
                        .HasForeignKey("UniversityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniScheduler.Domain.Entities.AppUser", "User")
                        .WithMany("UniversityAccesses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("University");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UniScheduler.Domain.Entities.AppUser", b =>
                {
                    b.Navigation("UniversityAccesses");
                });

            modelBuilder.Entity("UniScheduler.Domain.Entities.Building", b =>
                {
                    b.Navigation("DistancesFrom");

                    b.Navigation("DistancesTo");

                    b.Navigation("FloorPlanEdges");

                    b.Navigation("FloorPlanNodes");

                    b.Navigation("FloorPlans");

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("UniScheduler.Domain.Entities.CalendarPlan", b =>
                {
                    b.Navigation("StudyPlans");

                    b.Navigation("Weeks");
                });

            modelBuilder.Entity("UniScheduler.Domain.Entities.Department", b =>
                {
                    b.Navigation("Rooms");

                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("UniScheduler.Domain.Entities.Faculty", b =>
                {
                    b.Navigation("Departments");

                    b.Navigation("Groups");
                });

            modelBuilder.Entity("UniScheduler.Domain.Entities.FloorPlanNode", b =>
                {
                    b.Navigation("Connections");

                    b.Navigation("EdgesFrom");

                    b.Navigation("EdgesTo");
                });

            modelBuilder.Entity("UniScheduler.Domain.Entities.Room", b =>
                {
                    b.Navigation("ScheduleEntries");
                });

            modelBuilder.Entity("UniScheduler.Domain.Entities.Schedule", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("UniScheduler.Domain.Entities.ScheduleEntry", b =>
                {
                    b.Navigation("StudentGroups");
                });

            modelBuilder.Entity("UniScheduler.Domain.Entities.StudentGroup", b =>
                {
                    b.Navigation("BlockedDays");

                    b.Navigation("ScheduleEntryGroups");
                });

            modelBuilder.Entity("UniScheduler.Domain.Entities.StudyPlan", b =>
                {
                    b.Navigation("Entries");

                    b.Navigation("Groups");
                });

            modelBuilder.Entity("UniScheduler.Domain.Entities.Subject", b =>
                {
                    b.Navigation("ScheduleEntries");

                    b.Navigation("TeacherSubjects");
                });

            modelBuilder.Entity("UniScheduler.Domain.Entities.Teacher", b =>
                {
                    b.Navigation("Availabilities");

                    b.Navigation("ScheduleEntries");

                    b.Navigation("TeacherSubjects");
                });

            modelBuilder.Entity("UniScheduler.Domain.Entities.University", b =>
                {
                    b.Navigation("Buildings");

                    b.Navigation("CalendarPlans");

                    b.Navigation("Faculties");

                    b.Navigation("SolverSettings");

                    b.Navigation("Teachers");

                    b.Navigation("UserAccesses");
                });
#pragma warning restore 612, 618
        }
    }
}
