// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UniScheduler.Infrastructure.Persistence;

#nullable disable

namespace UniScheduler.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260512150009_FacultyAndScheduleRestructure")]
    partial class FacultyAndScheduleRestructure
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UniScheduler.Domain.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("TeacherId")
                        .HasColumnType("uuid");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("UniScheduler.Domain.Entities.Building", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShortCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("StairsDistancePerFloor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(20);

                    b.HasKey("Id");

                    b.ToTable("Buildings");
                });

            modelBuilder.Entity("UniScheduler.Domain.Entities.BuildingDistance", b =>
                {
                    b.Property<Guid>("FromBuildingId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ToBuildingId")
                        .HasColumnType("uuid");

                    b.Property<int>("DistanceMeters")
                        .HasColumnType("integer");

                    b.HasKey("FromBuildingId", "ToBuildingId");

                    b.HasIndex("ToBuildingId");

                    b.ToTable("BuildingDistances");
                });

            modelBuilder.Entity("UniScheduler.Domain.Entities.Faculty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ShortCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("ShortCode")
                        .IsUnique();

                    b.ToTable("Faculties");
                });

            modelBuilder.Entity("UniScheduler.Domain.Entities.RescheduleRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdminNote")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OriginalEntryId")
                        .HasColumnType("uuid");

                    b.Property<int?>("ProposedDayOfWeek")
                        .HasColumnType("integer");

                    b.Property<int?>("ProposedPairNumber")
                        .HasColumnType("integer");

                    b.Property<int?>("ProposedWeekType")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RequestedByTeacherId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OriginalEntryId");

                    b.HasIndex("RequestedByTeacherId");

                    b.ToTable("RescheduleRequests");
                });

            modelBuilder.Entity("UniScheduler.Domain.Entities.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BuildingId")
                        .HasColumnType("uuid");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<int>("DistanceFromStairsMeters")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("Floor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<bool>("HasComputers")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasLab")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasProjector")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("boolean");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("RoomType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("UniScheduler.Domain.Entities.Schedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AcademicYear")
                        .HasColumnType("integer");

                    b.Property<bool>("AllowCrossFacultyLessons")
                        .HasColumnType("boolean");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<Guid?>("FacultyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GenerationNotes")
                        .HasColumnType("text");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Term")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FacultyId");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("UniScheduler.Domain.Entities.ScheduleEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("boolean");

                    b.Property<int>("LessonType")
                        .HasColumnType("integer");

                    b.Property<int>("PairNumber")
                        .HasColumnType("integer");

                    b.Property<Guid?>("RoomId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uuid");

                    b.Property<int>("WeekType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherId");

                    b.HasIndex("ScheduleId", "RoomId", "DayOfWeek", "PairNumber", "WeekType")
                        .IsUnique()
                        .HasFilter("\"RoomId\" IS NOT NULL");

                    b.HasIndex("ScheduleId", "TeacherId", "DayOfWeek", "PairNumber", "WeekType")
                        .IsUnique();

                    b.ToTable("ScheduleEntries");
                });

            modelBuilder.Entity("UniScheduler.Domain.Entities.ScheduleEntryStudentGroup", b =>
                {
                    b.Property<Guid>("ScheduleEntryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StudentGroupId")
                        .HasColumnType("uuid");

                    b.HasKey("ScheduleEntryId", "StudentGroupId");

                    b.HasIndex("StudentGroupId");

                    b.ToTable("ScheduleEntryStudentGroups");
                });

            modelBuilder.Entity("UniScheduler.Domain.Entities.StudentGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("FacultyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StudentCount")
                        .HasColumnType("integer");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FacultyId");

                    b.ToTable("StudentGroups");
                });

            modelBuilder.Entity("UniScheduler.Domain.Entities.Subject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AcademicYear")
                        .HasColumnType("integer");

                    b.Property<double>("LabHoursPerWeek")
                        .HasColumnType("double precision");

                    b.Property<int>("LabWeekType")
                        .HasColumnType("integer");

                    b.Property<double>("LectureHoursPerWeek")
                        .HasColumnType("double precision");

                    b.Property<int>("LectureWeekType")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("PracticalHoursPerWeek")
                        .HasColumnType("double precision");

                    b.Property<int>("PracticalWeekType")
                        .HasColumnType("integer");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Term")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("UniScheduler.Domain.Entities.Teacher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("UniScheduler.Domain.Entities.TeacherAvailability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("boolean");

                    b.Property<int>("PairNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("ValidFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ValidTo")
                        .HasColumnType("date");

                    b.Property<int>("WeekType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.ToTable("TeacherAvailabilities");
                });

            modelBuilder.Entity("UniScheduler.Domain.Entities.TeacherSubject", b =>
                {
                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid");

                    b.Property<int>("LessonType")
                        .HasColumnType("integer");

                    b.Property<int?>("PreferredRoomType")
                        .HasColumnType("integer");

                    b.HasKey("TeacherId", "SubjectId", "LessonType");

                    b.HasIndex("SubjectId");

                    b.ToTable("TeacherSubjects");
                });

            modelBuilder.Entity("UniScheduler.Domain.Entities.AppUser", b =>
                {
                    b.HasOne("UniScheduler.Domain.Entities.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("UniScheduler.Domain.Entities.BuildingDistance", b =>
                {
                    b.HasOne("UniScheduler.Domain.Entities.Building", "FromBuilding")
                        .WithMany("DistancesFrom")
                        .HasForeignKey("FromBuildingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UniScheduler.Domain.Entities.Building", "ToBuilding")
                        .WithMany("DistancesTo")
                        .HasForeignKey("ToBuildingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromBuilding");

                    b.Navigation("ToBuilding");
                });

            modelBuilder.Entity("UniScheduler.Domain.Entities.RescheduleRequest", b =>
                {
                    b.HasOne("UniScheduler.Domain.Entities.ScheduleEntry", "OriginalEntry")
                        .WithMany()
                        .HasForeignKey("OriginalEntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UniScheduler.Domain.Entities.Teacher", "RequestedByTeacher")
                        .WithMany()
                        .HasForeignKey("RequestedByTeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OriginalEntry");

                    b.Navigation("RequestedByTeacher");
                });

            modelBuilder.Entity("UniScheduler.Domain.Entities.Room", b =>
                {
                    b.HasOne("UniScheduler.Domain.Entities.Building", "Building")
                        .WithMany("Rooms")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Building");
                });

            modelBuilder.Entity("UniScheduler.Domain.Entities.Schedule", b =>
                {
                    b.HasOne("UniScheduler.Domain.Entities.Faculty", "Faculty")
                        .WithMany()
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Faculty");
                });

            modelBuilder.Entity("UniScheduler.Domain.Entities.ScheduleEntry", b =>
                {
                    b.HasOne("UniScheduler.Domain.Entities.Room", "Room")
                        .WithMany("ScheduleEntries")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("UniScheduler.Domain.Entities.Schedule", "Schedule")
                        .WithMany("Entries")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniScheduler.Domain.Entities.Subject", "Subject")
                        .WithMany("ScheduleEntries")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UniScheduler.Domain.Entities.Teacher", "Teacher")
                        .WithMany("ScheduleEntries")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("Schedule");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("UniScheduler.Domain.Entities.ScheduleEntryStudentGroup", b =>
                {
                    b.HasOne("UniScheduler.Domain.Entities.ScheduleEntry", "ScheduleEntry")
                        .WithMany("StudentGroups")
                        .HasForeignKey("ScheduleEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniScheduler.Domain.Entities.StudentGroup", "StudentGroup")
                        .WithMany("ScheduleEntryGroups")
                        .HasForeignKey("StudentGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ScheduleEntry");

                    b.Navigation("StudentGroup");
                });

            modelBuilder.Entity("UniScheduler.Domain.Entities.StudentGroup", b =>
                {
                    b.HasOne("UniScheduler.Domain.Entities.Faculty", "Faculty")
                        .WithMany("Groups")
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Faculty");
                });

            modelBuilder.Entity("UniScheduler.Domain.Entities.TeacherAvailability", b =>
                {
                    b.HasOne("UniScheduler.Domain.Entities.Teacher", "Teacher")
                        .WithMany("Availabilities")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("UniScheduler.Domain.Entities.TeacherSubject", b =>
                {
                    b.HasOne("UniScheduler.Domain.Entities.Subject", "Subject")
                        .WithMany("TeacherSubjects")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniScheduler.Domain.Entities.Teacher", "Teacher")
                        .WithMany("TeacherSubjects")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("UniScheduler.Domain.Entities.Building", b =>
                {
                    b.Navigation("DistancesFrom");

                    b.Navigation("DistancesTo");

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("UniScheduler.Domain.Entities.Faculty", b =>
                {
                    b.Navigation("Groups");
                });

            modelBuilder.Entity("UniScheduler.Domain.Entities.Room", b =>
                {
                    b.Navigation("ScheduleEntries");
                });

            modelBuilder.Entity("UniScheduler.Domain.Entities.Schedule", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("UniScheduler.Domain.Entities.ScheduleEntry", b =>
                {
                    b.Navigation("StudentGroups");
                });

            modelBuilder.Entity("UniScheduler.Domain.Entities.StudentGroup", b =>
                {
                    b.Navigation("ScheduleEntryGroups");
                });

            modelBuilder.Entity("UniScheduler.Domain.Entities.Subject", b =>
                {
                    b.Navigation("ScheduleEntries");

                    b.Navigation("TeacherSubjects");
                });

            modelBuilder.Entity("UniScheduler.Domain.Entities.Teacher", b =>
                {
                    b.Navigation("Availabilities");

                    b.Navigation("ScheduleEntries");

                    b.Navigation("TeacherSubjects");
                });
#pragma warning restore 612, 618
        }
    }
}
